import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  skill: [
    'skill/introduction',
    {
      label: '云笔记配置',
      type: 'category',
      link: {
        type: 'doc',
        id: 'skill/cloud-note/cloud-note-guides',
      },
      items: [
        'skill/cloud-note/cloud-note-config',
        'skill/cloud-note/cloud-note-console',
        'skill/cloud-note/cloud-note-add-note',
        'skill/cloud-note/cloud-note-explain',
        'skill/cloud-note/cloud-note-markdown-syntax',
      ],
    },
    {
      label: '云笔记部署',
      type: 'category',
      link: {
        type: 'doc',
        id: 'skill/docusaurus/docusaurus-guides',
      },
      items: [
        'skill/docusaurus/docusaurus-config',
        'skill/docusaurus/docusaurus-style',
        'skill/docusaurus/docusaurus-component',
        'skill/docusaurus/docusaurus-plugin',
        'skill/docusaurus/docusaurus-search',
        'skill/docusaurus/docusaurus-comment',
        'skill/docusaurus/docusaurus-deploy',
      ],
    },
    {
      label: 'Web',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          label: 'Vue',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            'skill/web/vue/vue-reactive-data-object',
            'skill/web/vue/vue-reactive-data-array',
            'skill/web/vue/vue-reactive-data-basic-type',
            'skill/web/vue/pinia',
          ],
        },
        {
          label: 'React',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/web/react',
            },
          ],
        },
        {
          label: 'Css',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/web/css',
            },
          ],
        },
        {
          label: 'Browser',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/web/browser',
            },
          ],
        },
      ],
    },
    {
      label: 'Git',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/git',
        },
      ],
    },
    {
      label: 'windows',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/windows',
        }
      ]
    },
    {
      label: '路由与交换',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/ensp',
        }
      ]
    },
    {
      label: '前端',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/front',
        }
      ]
    },
  ],
  tools: [
    'tools/introduction',
    'tools/everything-quick-search-local-files',
    'tools/wappalyzer-recognize-technology',
    'tools/windows-custom-right-click-menu',
    'tools/vscode-config',
    'tools/idea-config',
    'tools/vite-plugin',
    'tools/jetbrains-product-activation-method',
    'tools/test'
  ],
}

module.exports = sidebars
